version: "3.8"

services:
  # Ollama LLM server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./backend/src/main/resources/Modelfiles:/root/Modelfiles
    entrypoint: /bin/sh
    command: -c "for file in /root/Modelfiles/*.txt; do modelname=$(basename \"$file\" .txt); if ! ollama list | grep -q \"$modelname\"; then echo \"▼ Creating model $modelname from $file...\"; ollama create \"$modelname\" -f \"$file\"; fi; done; exec ollama serve"
    restart: unless-stopped

  # Spring Boot backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped

volumes:
  ollama-data:
