services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./backend/src/main/resources/Modelfiles:/root/Modelfiles:ro
    entrypoint: /bin/sh -c "
      ollama serve & sleep 8;
      for f in /root/Modelfiles/*.txt; do
        m=$$(basename \"$$f\" .txt);
        if ! ollama list | grep -q \"^$$m[ ]\"; then
          ollama create \"$$m\" -f \"$$f\";
        fi;
      done;
      tail -f /dev/null"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  
    depends_on:
      - backend
    profiles: ["frontend"] 

volumes:
  ollama-data:
