services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./backend/src/main/resources/Modelfiles:/root/Modelfiles:ro
    entrypoint: /bin/sh -c "
      ollama serve & sleep 8;
      for f in /root/Modelfiles/*.txt; do
        m=$$(basename \"$$f\" .txt);
        if ! ollama list | grep -q \"^$$m[ ]\"; then
          ollama create \"$$m\" -f \"$$f\";
        fi;
      done;
      tail -f /dev/null"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tecmap-ai-db
      POSTGRES_USER: tecmap_user
      POSTGRES_PASSWORD: password
      TZ: America/New_York
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [ backend ]

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - ollama
      - db
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tecmap-ai-db
      - SPRING_DATASOURCE_USERNAME=tecmap_user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: unless-stopped
    networks: [backend]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  
    depends_on:
      - backend
    profiles: ["frontend"]
    networks: [backend]

volumes:
  ollama-data:
  h2-data:
  db-data:

networks:
  backend: